### ISSUE TITLE
Can't open: Unknown error (0xC1)

### ISSUE THREAD

**Issue by V1rtu0l** [jamesmth/llvm-plugin-rs#12]
![image](https://github.com/user-attachments/assets/e9b5c108-b54f-4f1c-bee9-652d26af48eb)
Hello, just like the above picture error, why is this

**Comment by jamesmth** [comment]
Hi,
No idea, and the only thread I found while googling the problem was https://lists.llvm.org/pipermail/cfe-dev/2017-July/054808.html.

However, the bigger issue you have is that, **on Windows, the LLVM toolchain used by `rustc` is not compiled with plugin support**. Therefore, using the `-Zllvm-plugins`/`-Cpasses` flags of `rustc` is most likely undefined behavior.

To fix this, I suggest you take a look at this [LLVM fork](https://github.com/jamesmth/llvm-project) I made for this specific purpose. Instead of using the `-Zllvm-plugins`/`-Cpasses` flags, you would use the `lld` linker (from the fork) on Windows, and use your LLVM plugin as an LTO LLVM plugin.

**Comment by V1rtu0l** [comment]
Thank you for your reply. Is there a more detailed usage document on windows? Because I failed to use it according to the existing information, thank you again

**Comment by jamesmth** [comment]
You're welcome!
Last time I checked, the LLVM community doesn't talk much about LLVM plugins support on Windows, and the only useful information I found about it was this patch request: https://reviews.llvm.org/D18826?id=53036.

Also, I'm not sure the rustc maintainers have even bothered to document the fact that '-Zllvm-plugins' and '-Cpasses' won't work on Windows.

So, as you may have noticed, information is very thin on the subject. The way I discovered how to make it all work was by reading the LLVM sources and playing with various linker-related flags of rustc...
