### ISSUE TITLE
[question] is there a way to register the custom pass in inkwell's passmanager?

### ISSUE THREAD

**Issue by Chronostasys** [jamesmth/llvm-plugin-rs#4]
Hi, I'm building a compiler using inkwell, and want to add some custom passes to the inkwell's `PassManager` like below:  
![image](https://user-images.githubusercontent.com/49905799/216006960-008c1aee-6068-4b08-b2e4-f0c8f69f682f.png)

Is there any way to do so?

**Comment by jamesmth** [comment]
Hi,

There is no way to do so with this crate, because its only purpose is to compile custom passes into an LLVM plugin.

On the other hand, `inkwell` is merely a wrapper over the C-API of LLVM. Therefore, I believe the only way to achieve what you want would be to integrate your custom pass into your own LLVM fork. Then, you would have to patch `inkwell` to add a new method for the `PassManager` struct, something like `PassManager::add_my_custom_pass()`.

**Comment by Chronostasys** [comment]
Thanks very much.
